[tool.poetry]
name = "calarmhelp"
version = "0.1.0"
description = ""
authors = ["Dashinja <byron@dashinja.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain-openai = "^0.1.3"
python-dotenv = "^1.0.1"
flake8 = "^7.0.0"
pyproject-flake8 = "^7.0.0"
pydantic = "^2.7.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
fastapi = "^0.110.1"
langchain = "^0.1.16"
langchain-core = "^0.1.45"
langchain-community = "^0.0.34"

[tool.poetry.scripts]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
